### ISSUE TITLE
Usage example for hot corners

### ISSUE THREAD

**Issue by rchastain** [tothpaul/Delphi-LowLevel#1]
Hello Paul!

Could you explain how to use the hot corners program?

When I try to start the compiled program, nothing seems to happen.

Regards.

Roland

**Comment by tothpaul** [comment]
Hi,

You should look at the original project :)

but when the mouse stay for 300ms in the top left of the screen, the application automaticaly stike the Win+Tab keys (under Windows 10 it display all the active applications).

you can also hit Ctrl+Alt+C  to exit the application.

kCornerInput define the sequence of keys
KHotKey and kHotKeyModifiers define the exit sequence.

(je peux te l'expliquer en français aussi ;) )

Paul

**Comment by rchastain** [comment]
Vu. Merci Paul !
